---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
  namespace: whoami
  labels:
    "use-http01-solver": "true"
spec:
  commonName: whoami.bluetrusty.eu
  secretName: whoami-cert
  dnsNames:
    - whoami.bluetrusty.eu
  issuerRef:
    name: letsencrypt-staging
    ##     name: letsencrypt-prod
    kind: ClusterIssuer
